apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-demo-hello-world-golang-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/developer-guy/tekton-demo-hello-world-golang
